export const SOUTH_KOREA_STATE_DIRECTION = {
  NORTH: '북',
  SOUTH: '남',
} as const;

export type SouthKoreaStateDirection = (typeof SOUTH_KOREA_STATE_DIRECTION)[keyof typeof SOUTH_KOREA_STATE_DIRECTION];

export const SOUTH_KOREA_STATE_CLASSIFIER = {
  SPECIAL: '특별',
  AUTONOMY: '자치',
  METROPOLITAN: '광역',
} as const;

export type SouthKoreaStateClassifier = (typeof SOUTH_KOREA_STATE_CLASSIFIER)[keyof typeof SOUTH_KOREA_STATE_CLASSIFIER];

export const SOUTH_KOREA_STATE_LEVEL = {
  DO: '도',
  SI: '시',
} as const;

export type SouthKoreaStateLevel = (typeof SOUTH_KOREA_STATE_LEVEL)[keyof typeof SOUTH_KOREA_STATE_LEVEL];

export const SOUTH_KOREA_STATE_NAME = {
  //#region 특별시
  SEOUL: '서울',
  //#endregion

  //#region 광역시
  BUSAN: '부산',
  DAEGU: '대구',
  INCHEON: '인천',
  GWANGJU: '광주',
  DAEJEON: '대전',
  ULSAN: '울산',
  //#endregion

  //#region 특별자치시
  SEJONG: '세종',
  //#endregion

  //#region 도
  GYEONGGI: '경기',
  CHUNGCHEONG: '충청',
  JEONRA: '전라',
  GYEONGSANG: '경상',
  //#endregion

  //#region 특별자치도
  GANGWON: '강원',
  JEONBUK: '전북',
  JEJU: '제주',
  //#endregion
} as const;

export type SouthKoreaStateName = (typeof SOUTH_KOREA_STATE_NAME)[keyof typeof SOUTH_KOREA_STATE_NAME];

export const SOUTH_KOREA_STATE_FULL_NAME = {
  //#region 특별시
  SEOUL: `${SOUTH_KOREA_STATE_NAME.SEOUL}${SOUTH_KOREA_STATE_CLASSIFIER.SPECIAL}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  //#endregion

  //#region 광역시
  BUSAN: `${SOUTH_KOREA_STATE_NAME.BUSAN}${SOUTH_KOREA_STATE_CLASSIFIER.METROPOLITAN}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  DAEGU: `${SOUTH_KOREA_STATE_NAME.DAEGU}${SOUTH_KOREA_STATE_CLASSIFIER.METROPOLITAN}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  INCHEON: `${SOUTH_KOREA_STATE_NAME.INCHEON}${SOUTH_KOREA_STATE_CLASSIFIER.METROPOLITAN}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  GWANGJU: `${SOUTH_KOREA_STATE_NAME.GWANGJU}${SOUTH_KOREA_STATE_CLASSIFIER.METROPOLITAN}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  DAEJEON: `${SOUTH_KOREA_STATE_NAME.DAEJEON}${SOUTH_KOREA_STATE_CLASSIFIER.METROPOLITAN}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  ULSAN: `${SOUTH_KOREA_STATE_NAME.ULSAN}${SOUTH_KOREA_STATE_CLASSIFIER.METROPOLITAN}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  //#endregion

  //#region 특별자치시
  SEJONG: `${SOUTH_KOREA_STATE_NAME.SEJONG}${SOUTH_KOREA_STATE_CLASSIFIER.SPECIAL}${SOUTH_KOREA_STATE_CLASSIFIER.AUTONOMY}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  //#endregion

  //#region 도
  GYEONGGI: `${SOUTH_KOREA_STATE_NAME.GYEONGGI}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  NORTH_CHUNGCHEONG: `${SOUTH_KOREA_STATE_NAME.CHUNGCHEONG}${SOUTH_KOREA_STATE_DIRECTION.NORTH}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  SOUTH_CHUNGCHEONG: `${SOUTH_KOREA_STATE_NAME.CHUNGCHEONG}${SOUTH_KOREA_STATE_DIRECTION.SOUTH}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  SOUTH_JEONRA: `${SOUTH_KOREA_STATE_NAME.JEONRA}${SOUTH_KOREA_STATE_DIRECTION.SOUTH}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  NORTH_GYEONGSANG: `${SOUTH_KOREA_STATE_NAME.GYEONGSANG}${SOUTH_KOREA_STATE_DIRECTION.NORTH}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  SOUTH_GYEONGSANG: `${SOUTH_KOREA_STATE_NAME.GYEONGSANG}${SOUTH_KOREA_STATE_DIRECTION.SOUTH}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  //#endregion

  //#region 특별자치도
  GANGWON: `${SOUTH_KOREA_STATE_NAME.GANGWON}${SOUTH_KOREA_STATE_CLASSIFIER.SPECIAL}${SOUTH_KOREA_STATE_CLASSIFIER.AUTONOMY}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  JEONBUK: `${SOUTH_KOREA_STATE_NAME.JEONBUK}${SOUTH_KOREA_STATE_CLASSIFIER.SPECIAL}${SOUTH_KOREA_STATE_CLASSIFIER.AUTONOMY}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  JEJU: `${SOUTH_KOREA_STATE_NAME.JEJU}${SOUTH_KOREA_STATE_CLASSIFIER.SPECIAL}${SOUTH_KOREA_STATE_CLASSIFIER.AUTONOMY}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  //#endregion
} as const;

export type SouthKoreaStateFullName = (typeof SOUTH_KOREA_STATE_FULL_NAME)[keyof typeof SOUTH_KOREA_STATE_FULL_NAME];

export const SOUTH_KOREA_STATE_ALTERNATIVE_NAMES = {
  //#region 특별시
  SEOUL: [SOUTH_KOREA_STATE_NAME.SEOUL, SOUTH_KOREA_STATE_FULL_NAME.SEOUL, `${SOUTH_KOREA_STATE_NAME.SEOUL}${SOUTH_KOREA_STATE_LEVEL.SI}`],
  //#endregion

  //#region 광역시
  BUSAN: [SOUTH_KOREA_STATE_NAME.BUSAN, SOUTH_KOREA_STATE_FULL_NAME.BUSAN, `${SOUTH_KOREA_STATE_NAME.BUSAN}${SOUTH_KOREA_STATE_LEVEL.SI}`],
  DAEGU: [SOUTH_KOREA_STATE_NAME.DAEGU, SOUTH_KOREA_STATE_FULL_NAME.DAEGU, `${SOUTH_KOREA_STATE_NAME.DAEGU}${SOUTH_KOREA_STATE_LEVEL.SI}`],
  INCHEON: [
    SOUTH_KOREA_STATE_NAME.INCHEON,
    SOUTH_KOREA_STATE_FULL_NAME.INCHEON,
    `${SOUTH_KOREA_STATE_NAME.INCHEON}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  ],
  GWANGJU: [
    SOUTH_KOREA_STATE_NAME.GWANGJU,
    SOUTH_KOREA_STATE_FULL_NAME.GWANGJU,
    `${SOUTH_KOREA_STATE_NAME.GWANGJU}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  ],
  DAEJEON: [
    SOUTH_KOREA_STATE_NAME.DAEJEON,
    SOUTH_KOREA_STATE_FULL_NAME.DAEJEON,
    `${SOUTH_KOREA_STATE_NAME.DAEJEON}${SOUTH_KOREA_STATE_LEVEL.SI}`,
  ],
  ULSAN: [SOUTH_KOREA_STATE_NAME.ULSAN, SOUTH_KOREA_STATE_FULL_NAME.ULSAN, `${SOUTH_KOREA_STATE_NAME.ULSAN}${SOUTH_KOREA_STATE_LEVEL.SI}`],
  //#endregion

  //#region 특별자치시
  SEJONG: [SOUTH_KOREA_STATE_NAME.SEJONG, SOUTH_KOREA_STATE_FULL_NAME.SEJONG],
  //#endregion

  //#region 도
  GYEONGGI: [SOUTH_KOREA_STATE_NAME.GYEONGGI, SOUTH_KOREA_STATE_FULL_NAME.GYEONGGI],
  NORTH_CHUNGCHEONG: [
    SOUTH_KOREA_STATE_FULL_NAME.NORTH_CHUNGCHEONG,
    `${SOUTH_KOREA_STATE_NAME.CHUNGCHEONG.at(0)}${SOUTH_KOREA_STATE_DIRECTION.NORTH}` as '충북',
  ],
  SOUTH_CHUNGCHEONG: [
    SOUTH_KOREA_STATE_FULL_NAME.SOUTH_CHUNGCHEONG,
    `${SOUTH_KOREA_STATE_NAME.CHUNGCHEONG.at(0)}${SOUTH_KOREA_STATE_DIRECTION.SOUTH}` as '충남',
  ],
  SOUTH_JEONRA: [
    SOUTH_KOREA_STATE_FULL_NAME.SOUTH_JEONRA,
    `${SOUTH_KOREA_STATE_NAME.JEONRA.at(0)}${SOUTH_KOREA_STATE_DIRECTION.SOUTH}` as '전남',
  ],
  NORTH_GYEONGSANG: [
    SOUTH_KOREA_STATE_FULL_NAME.NORTH_GYEONGSANG,
    `${SOUTH_KOREA_STATE_NAME.GYEONGSANG.at(0)}${SOUTH_KOREA_STATE_DIRECTION.NORTH}` as '경북',
  ],
  SOUTH_GYEONGSANG: [
    SOUTH_KOREA_STATE_FULL_NAME.SOUTH_GYEONGSANG,
    `${SOUTH_KOREA_STATE_NAME.GYEONGSANG.at(0)}${SOUTH_KOREA_STATE_DIRECTION.SOUTH}` as '경남',
  ],
  //#endregion

  //#region 특별자치도
  GANGWON: [
    SOUTH_KOREA_STATE_NAME.GANGWON,
    SOUTH_KOREA_STATE_FULL_NAME.GANGWON,
    `${SOUTH_KOREA_STATE_NAME.GANGWON}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  ],
  JEONBUK: [
    SOUTH_KOREA_STATE_NAME.JEONBUK,
    SOUTH_KOREA_STATE_FULL_NAME.JEONBUK,
    `${SOUTH_KOREA_STATE_NAME.JEONBUK}${SOUTH_KOREA_STATE_LEVEL.DO}`,
  ],
  JEJU: [SOUTH_KOREA_STATE_NAME.JEJU, SOUTH_KOREA_STATE_FULL_NAME.JEJU, `${SOUTH_KOREA_STATE_NAME.JEJU}${SOUTH_KOREA_STATE_LEVEL.DO}`],
  //#endregion
} as const;

export type SouthKoreaStateAlternativeNames =
  (typeof SOUTH_KOREA_STATE_ALTERNATIVE_NAMES)[keyof typeof SOUTH_KOREA_STATE_ALTERNATIVE_NAMES];
